### ISSUE TITLE
uqmi_2021-12-22-0.2_mipsel_24kc.ipk install problem on openwrt 19.07.8

### ISSUE THREAD

**Issue by snowrice** [mrhaav/openwrt#1]
Collected errors:
 * pkg_init_from_file: Malformed package file /tmp/uqmi_2021-12-22-0.2_mipsel_24kc.ipk.
 

How can I install the ipk file on my openwrt 19.07.8 Router?

**Comment by snowrice** [comment]
Yes, it works.
One problem I found was the 4G module /dev/cdc-wdm0 is missiing after hot reboot the router(reboot in luci or ssh ). Cold boot is no problem at all

**Comment by Organarh** [comment]
root@OpenWrt:~# opkg update && opkg install kmod-usb-serial
Installing kmod-usb-serial (4.14.241-1) to root...
Downloading http://downloads.openwrt.org/releases/19.07.8/targets/ramips/mt76x8/packages/kmod-usb-serial_4.14.241-1_mipsel_24kc.ipk
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-usb-serial:
 *      kernel (= 4.14.241-1-d92769dc5268e102503ae83fe968a56c)
 * opkg_install_cmd: Cannot install package kmod-usb-serial.
 
How to install kmod-usb-serial, I need it.

**Comment by mrhaav** [comment]
Hi
Will this work:
```
wget https://github.com/mrhaav/openwrt/raw/master/MR200v4/kmod-usb-serial_4.14.241-1_mipsel_24kc.ipk
opkg install kmod-usb-serial_4.14.241-1_mipsel_24kc.ipk
```

**Comment by Organarh** [comment]
No it doesn't work.
root@OpenWrt:~# wget https://github.com/mrhaav/openwrt/raw/master/MR200v4/kmod-usb-serial_4.14.241-1_mipsel_24kc.ipk
Downloading 'https://github.com/mrhaav/openwrt/raw/master/MR200v4/kmod-usb-serial_4.14.241-1_mipsel_24kc.ipk'
Connecting to 140.82.121.3:443
Redirected to /mrhaav/openwrt/master/MR200v4/kmod-usb-serial_4.14.241-1_mipsel_24kc.ipk on raw.githubusercontent.com
Writing to 'kmod-usb-serial_4.14.241-1_mipsel_24kc.ipk'
kmod-usb-serial_4.14 100% |*******************************| 13675   0:00:00 ETA
Download completed (13675 bytes)

root@OpenWrt:~# opkg install kmod-usb-serial_4.14.241-1_mipsel_24kc.ipk
Installing kmod-usb-serial (4.14.241-1) to root...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-usb-serial:
 *      kernel (= 4.14.241-1-d92769dc5268e102503ae83fe968a56c)
 * opkg_install_cmd: Cannot install package kmod-usb-serial.

**Comment by Organarh** [comment]
I have tried and even tried.
root@OpenWrt:~# opkg install comgt kmod-usb-serial kmod-usb-serial-option kmod-usb-serial-wwan usb-modeswitch usb-modeswitch-data
Package comgt (0.32-33) installed in root is up to date.
Installing kmod-usb-serial (4.14.241-1) to root...
Downloading http://downloads.openwrt.org/releases/19.07.8/targets/ramips/mt76x8/packages/kmod-usb-serial_4.14.241-1_mipsel_24kc.ipk
Installing kmod-usb-serial-option (4.14.241-1) to root...
Downloading http://downloads.openwrt.org/releases/19.07.8/targets/ramips/mt76x8/packages/kmod-usb-serial-option_4.14.241-1_mipsel_24kc.ipk
Package kmod-usb-serial-wwan (4.14.241-1) installed in root is up to date.
Package usb-modeswitch (2017-12-19-f40f84c2-2) installed in root is up to date.
Unknown package 'usb-modeswitch-data'.
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-usb-serial:
 *      kernel (= 4.14.241-1-d92769dc5268e102503ae83fe968a56c)
 * opkg_install_cmd: Cannot install package kmod-usb-serial.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-usb-serial-option:
 *      kernel (= 4.14.241-1-d92769dc5268e102503ae83fe968a56c)
 * opkg_install_cmd: Cannot install package kmod-usb-serial-option.
 * opkg_install_cmd: Cannot install package usb-modeswitch-data.

**Comment by Organarh** [comment]
In any case, many thanks for the assembly. Previously, no one was interested in this. I personally waited about 1 year.

**Comment by mrhaav** [comment]
What extra kmod packages do you need?
kmod-usb-serial
kmod-usb-serial-option

I could try to compile all again, but then you need to re-install our MR200v4.

**Comment by Organarh** [comment]
The bottom line is that you need to forward / dev / ttyUSB2 from the router to the PC.
tty USB ports
wwan libqmi kmod-usb-net kmod-usb-serial kmod-usb-serial-wwan kmod-usb-serial-option kmod-usb-serial-qualcomm luci-proto-qmi uqmi kmod-usb-wdm kmod-usb-net- qmi-wwan libmbim
+ socast

**Comment by Organarh** [comment]
You can also have these:
luci-app-modeminfo luci-app-smstools3 luci-app-atinout luci-app-mmconfig

**Comment by Organarh** [comment]
cd /tmp
opkg install --force-depends /tmp/ kmod-usb-serial_4.14.241-1_mipsel_24kc.ipk
root@OpenWrt:/# cd /
root@OpenWrt:/# /tmp/
-ash: /tmp/: Permission denied

**Comment by mrhaav** [comment]
Just for my curiosity, what are your goal?

I think it´s just the kmod- packages that are critical. All other should be possible to install.

**Comment by Organarh** [comment]
This is full modem control.
I am a simple user and I was told on this site that this is necessary.
https://4pda.to/forum/index.php?showtopic=994474&st=220#entry97866818

**Comment by Organarh** [comment]
luci-app-mmconfig
Probably the most long-awaited package. Hello Crox and Microdrive
Allows you to control the modem's frequency ranges through the mmcli utility

**Comment by Organarh** [comment]
Other settings are also required.

**Comment by mrhaav** [comment]
Isn´t your modem working? Or what do you need extra?

**Comment by Organarh** [comment]
Have you added packages?

**Comment by mrhaav** [comment]
Hi

Look here: https://github.com/mrhaav/openwrt/tree/master/MR200v4/test
I think you need to re-install.

**Comment by Organarh** [comment]
Thank you friend. After many attempts, I installed all the packages. I will study the openwrt settings.

**Comment by Organarh** [comment]
Hello, I ask for help. I did everything as indicated.
But my 4G network lights are not on? The second question is how can I upgrade to 21. .... version.???
