### ISSUE TITLE
Compile a Version for 21.02.7

### ISSUE THREAD

**Issue by xa-y-ax** [mrhaav/openwrt#10]
is it possible to compile a version for openwrt 21.02.7? 

i tried it with your 21.02.3 but it doesn't works with a vodafone germany sim:

`Wed Dec  6 09:56:13 2023 kern.info kernel: [ 1090.470722] rt3050-esw 10110000.esw: link changed 0x08
Wed Dec  6 09:56:27 2023 daemon.notice netifd: Interface 'wwan' is setting up now
Wed Dec  6 09:56:38 2023 daemon.notice netifd: wwan (3704): PINcode disabled
Wed Dec  6 09:56:38 2023 daemon.notice netifd: wwan (3704): Data format set to raw-ip
Wed Dec  6 09:56:38 2023 daemon.notice netifd: wwan (3704): Default profile: 1
Wed Dec  6 09:56:38 2023 daemon.notice netifd: wwan (3704): Initiate airplane mode
Wed Dec  6 09:56:40 2023 daemon.notice netifd: wwan (3704): Change default profile
Wed Dec  6 09:56:40 2023 daemon.notice netifd: wwan (3704):  authentication: chap to none
Wed Dec  6 09:56:40 2023 daemon.notice netifd: wwan (3704): Airplane mode off
Wed Dec  6 09:56:43 2023 kern.info kernel: [ 1119.667970] do_page_fault(): sending SIGSEGV to uqmi for invalid write access to 00000000
Wed Dec  6 09:56:43 2023 kern.info kernel: [ 1119.676360] epc = 77dcbbc4 in libc.so[77daa000+9c000]
Wed Dec  6 09:56:43 2023 kern.info kernel: [ 1119.681541] ra  = 00402fe1 in uqmi[400000+14000]
Wed Dec  6 09:56:43 2023 daemon.notice netifd: wwan (3704): Segmentation fault (core dumped)
Wed Dec  6 09:56:43 2023 daemon.notice netifd: wwan (3704): Failed to parse message data
Wed Dec  6 09:56:43 2023 daemon.notice netifd: wwan (3704):   on
`

**Comment by mrhaav** [comment]
Hi
What platform, or device, are you using?

**Comment by xa-y-ax** [comment]
I use the TP-Link TL-MR6400 v5 and try this old openwrt version to use the stable berlin freifunk firmware (http://selector.berlin.freifunk.net).
