### ISSUE TITLE
[SOLVED] File format is invalid or inconsistent

### ISSUE THREAD

**Issue by Trozmagon** [mrhaav/openwrt#13]
Anybody know why I would receive the error: **_File format is invalid or inconsistent_** when running? 

`apk add --allow-untrusted luci-proto-atc-2023.08.28-r2.apk`

This one worked okay:

`apk add --allow-untrusted atc-fib-fm350_gl-2024.11.18-r2.apk`

Thanks.

**Comment by mrhaav** [comment]
Hi

Did you download with:
`wget https://github.com/mrhaav/openwrt/raw/master/atc/luci-proto-atc-2023.08.28-r2.apk`
?

**Comment by Trozmagon** [comment]
Yeah

**Comment by Trozmagon** [comment]
Hmmm, a different error when trying this morning. I'm sure it's not the packages fault, it was just odd that the FM350-GL worked without hiccup .

![image](https://github.com/user-attachments/assets/84bcc484-f9a6-4997-9d28-45292e74c1a0)

**Comment by Trozmagon** [comment]
Hmmm, a different, more meaningful error now, seems related to the dependency **_atc-fib-fm350_gl-2024.11.18-r2_** not being installed but it is.

![image](https://github.com/user-attachments/assets/8b6d7adf-e552-4473-9941-e5a5f5d9f961)
![image](https://github.com/user-attachments/assets/43cb815b-1feb-46d9-8dcd-364f8a0f447d)

**Comment by Trozmagon** [comment]
Issue came down to the "/etc/apk/arch" file in OpenWRT, BPI-R4 snapshots only include "aarch64_cortex-a53", "all" was required to be added to as a secondary architecture for this to install.

**Comment by Trozmagon** [comment]
Solved
