### ISSUE TITLE
No source code provided.

### ISSUE THREAD

**Issue by gkourachanis** [mrhaav/openwrt#2]
Hello,

This repository is a fork of a foss project (uqmi) which is released under GPL version 2 ( or later ).
Can you please provide the changes you made so you respect the project's license and so other people can use it freely?
Maybe fork the upstream project and add the changes as commits. It would be really helpful.

Thanks

**Comment by mrhaav** [comment]
Hi
Source code are available at: https://github.com/mrhaav/openwrt-packages/tree/main/uqmi and description at https://github.com/mrhaav/openwrt-packages/blob/main/README.md.

Some of my changes are sent upstreams.

Or are there anything you are missing?

**Comment by gkourachanis** [comment]
Ok, thanks about those links. I assumed that the source code should have been together with the binary releases. But I guess that should work.

Cheers
