### ISSUE TITLE
MR200 teardown guide?

### ISSUE THREAD

**Issue by knuxify** [mrhaav/openwrt#3]
This probably isn't the best place to ask, but I'll ask anyways :p 

I have an MR200 v3, and from a cursory glance I suspect the hardware is nearly identical to the v4; so, I figured I'd try to probe around the system to get more information. For that, I'd need to access the serial pins, and to access them I'd need to take apart the router. Still, I just can't figure out how to take the device apart... I removed the two screws under the sticker but the top half just won't come off, and I'm worried about breaking the plastic fins...

Any tips on how to do it? I'd assume the case is similar for both models...

**Comment by mrhaav** [comment]
Hi
You have three fins on both sides. You have to use a thin screwdriver and try to push gently and lift at the same time. But it´s really easy to break the fins.
The serial pins are:
Black - ground
Orange - RX
Grey - TX
![CircuitBoard](https://user-images.githubusercontent.com/62175065/188285223-92aa4a1c-e1e5-433a-9527-8209f0ce1a20.jpg)
![Cover](https://user-images.githubusercontent.com/62175065/188285224-95526871-5e89-4d44-92de-8addf59df8a6.jpg)
![Fin](https://user-images.githubusercontent.com/62175065/188285231-27bd0e86-4ed5-4620-89ba-6c1e783ff168.jpg)

**Comment by knuxify** [comment]
Managed to open it (with a bit of force, but still...), and didn't break it in the process \o/ Thanks for the help!
