### ISSUE TITLE
MR6400 QMI not working on OpenWrt 22.03.2

### ISSUE THREAD

**Issue by fsufyan** [mrhaav/openwrt#4]
Hi Mrhaav,

I did an upgrade for my router yesterday. but since then your modified modem package refused to install.
Looks like there is and outdated dependency packages:
![Screenshot 2022-11-12 at 22 14 53](https://user-images.githubusercontent.com/36089616/201512414-0a6cc97d-7be8-41db-8f66-3187b2cccc03.png)

Also the updated package in the folder 22.03 is not installing, giving error:
`* pkg_init_from_file: Malformed package file uqmi_2022-09-13-0.9_mipsel_24kc.ipk.`

Any help would be appreciated.

**Comment by mrhaav** [comment]
Hi

I have now compiled a 22.03.2 version of mipsel_24kc, stored in folder 22.03.2. Can you try that one?

**Comment by fsufyan** [comment]
Ok, i'll try it, although i managed to get it working by using your source files for qmi daemon.

**Comment by fsufyan** [comment]
I get this error again:
`* pkg_init_from_file: Malformed package file uqmi_2022-09-13-0.9_mipsel_24kc.ipk.`

**Comment by mrhaav** [comment]
Did you download it with:
`wget https://github.com/mrhaav/openwrt/raw/master/22.03.2/uqmi_2022-09-13-0.9_mipsel_24kc.ipk`

**Comment by fsufyan** [comment]
This link now works.
Thank you very much.
