### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by tc-kirby** [mrhaav/openwrt#9]
I get -

 * pkg_init_from_file: Malformed package file uqmi_2022-11-29-0.11_mipsel_24kc.ipk.

**Comment by mrhaav** [comment]
Hi

Can you try download with:
`wget http://github.com/mrhaav/openwrt/raw/master/23.05.0/uqmi_2022-11-29-0.11_mipsel_24kc.ipk`
from your router?

**Comment by tc-kirby** [comment]
ok that installs now - thanks
